columns:
  Age:
    type: int
    description: Age of the insured person
    constraints:
      min: 18
      max: 100

  Gender:
    type: categorical
    description: Gender of the insured person
    categories:
      - Male
      - Female
      - Other

  BMI_Category:
    type: categorical
    description: Body mass index category of the insured person
    categories:
      - Underweight
      - Normal
      - Overweight
      - Obese

  Number_Of_Dependants:
    type: int
    description: Number of dependents covered by the insurance
    constraints:
      min: 0
      max: 10

  Smoking_Status:
    type: categorical
    description: Smoking status of the insured person
    categories:
      - Non-Smoker
      - Smoker

  Region:
    type: categorical
    description: Region where the insured person lives
    categories:
      - northeast
      - northwest
      - southeast
      - southwest

  Annual_Premium_Amount:
    type: float
    description: Insurance premium charges
    constraints:
      min: 0.0

  Marital_status:
    type: categorical
    description: Marital status of the insured person
    categories:
      - Single
      - Married
      - Divorced
      - Widowed

  Employment_Status:
    type: categorical
    description: Employment status of the insured person
    categories:
      - Employed
      - Self-employed
      - Unemployed
      - Retired

  Income_Level:
    type: categorical
    description: Income level of the insured person
    categories:
      - Low
      - Medium
      - High

  Income_Lakhs:
    type: float
    description: Income in lakhs
    constraints:
      min: 1.0
      max: 100.0

  Medical_History:
    type: categorical
    description: Medical history of the insured person
    categories:
      - None
      - Minor
      - Major

  Insurance_Plan:
    type: categorical
    description: Type of insurance plan
    categories:
      - Basic
      - Standard
      - Premium
      - Ultimate

target_column: Annual_Premium_Amount