# Azure Deployment Configuration

# Resource Group
resource_group:
  name: "insurance-premium-rg"
  location: "eastus"

# Azure Container Registry
container_registry:
  name: "insurancepremiumacr"
  sku: "Standard"
  admin_enabled: true

# Azure Machine Learning
azure_ml:
  workspace:
    name: "insurance-premium-ml"
    location: "eastus"
    sku: "basic"
  
  compute:
    # Compute instance for development
    instance:
      name: "insurance-dev-instance"
      vm_size: "Standard_DS3_v2"
      min_nodes: 0
      max_nodes: 1
    
    # Compute cluster for training
    cluster:
      name: "insurance-training-cluster"
      vm_size: "Standard_DS3_v2"
      min_nodes: 0
      max_nodes: 4
      idle_seconds_before_scaledown: 1800
  
  # Environment for model training and deployment
  environment:
    name: "insurance-premium-env"
    conda_file: "deployment/azure/conda_env.yml"
    docker_image: "mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest"
  
  # Model registration
  model:
    name: "insurance-premium-model"
    description: "Insurance Premium Prediction Model"
    tags:
      domain: "insurance"
      type: "regression"
  
  # Endpoints
  endpoints:
    # Real-time inference endpoint
    realtime:
      name: "insurance-premium-endpoint"
      vm_size: "Standard_DS2_v2"
      autoscale_enabled: true
      autoscale_min_replicas: 1
      autoscale_max_replicas: 3
      autoscale_target_utilization: 70
    
    # Batch inference endpoint
    batch:
      name: "insurance-premium-batch"
      compute_name: "insurance-training-cluster"

# Azure App Service
app_service:
  name: "insurance-premium-app"
  sku: "P1v2"
  always_on: true
  http20_enabled: true
  min_instances: 1
  max_instances: 3

# Azure Container Apps
container_apps:
  name: "insurance-premium-container-app"
  environment_name: "insurance-premium-env"
  min_replicas: 1
  max_replicas: 5
  target_utilization: 70
  ingress:
    external: true
    target_port: 8000

# Azure Key Vault
key_vault:
  name: "insurance-premium-kv"
  sku: "standard"
  secrets:
    - name: "db-connection-string"
    - name: "api-key"
    - name: "monitoring-key"

# Azure Monitor
monitoring:
  application_insights:
    name: "insurance-premium-insights"
  
  log_analytics:
    name: "insurance-premium-logs"
    retention_days: 30
  
  alerts:
    - name: "high-error-rate"
      description: "Alert when error rate exceeds threshold"
      severity: 2
      frequency: 5
      window_size: 5
      threshold: 5
      operator: "GreaterThan"
      metric_name: "requests/failed"
    
    - name: "high-latency"
      description: "Alert when response time exceeds threshold"
      severity: 2
      frequency: 5
      window_size: 5
      threshold: 1000
      operator: "GreaterThan"
      metric_name: "requests/duration"

# Azure Database (optional)
database:
  enabled: true
  type: "postgresql"
  name: "insurance-premium-db"
  sku: "GP_Gen5_2"
  storage_mb: 5120
  backup_retention_days: 7
  geo_redundant_backup: false

# Networking
networking:
  vnet:
    name: "insurance-premium-vnet"
    address_space: "10.0.0.0/16"
  
  subnet:
    name: "default"
    address_prefix: "10.0.0.0/24"
  
  nsg:
    name: "insurance-premium-nsg"
