artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_data: data/premiums.xlsx
  local_data_file: artifacts/data_ingestion/insurance.csv
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv
  validation_data_path: artifacts/data_ingestion/validation.csv

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  required_columns:
    - Age
    - Gender
    - BMI_Category
    - Number_Of_Dependants
    - Smoking_Status
    - Region
    - Annual_Premium_Amount
    - Marital_status
    - Employment_Status
    - Income_Level
    - Income_Lakhs
    - Medical_History
    - Insurance_Plan

data_transformation:
  root_dir: artifacts/data_transformation
  preprocessor_path: artifacts/data_transformation/preprocessor.joblib
  transformed_train_path: artifacts/data_transformation/train.csv
  transformed_test_path: artifacts/data_transformation/test.csv
  transformed_validation_path: artifacts/data_transformation/validation.csv

model_trainer:
  root_dir: artifacts/model_trainer
  model_path: artifacts/model_trainer/model.joblib
  train_metrics_path: artifacts/model_trainer/train_metrics.json
  test_metrics_path: artifacts/model_trainer/test_metrics.json

model_evaluation:
  root_dir: artifacts/model_evaluation
  metrics_path: artifacts/model_evaluation/metrics.json
  params_path: artifacts/model_evaluation/params.json